ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'EMERGENCY';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'SOLO_PARENT';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'MATERNITY';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'PATERNITY';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'BEREAVEMENT';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'MAGNA_CARTA_WOMEN';